# bugfix AHT caused some error, but i dont know what is this error. by AHT scripter yuyasato# i dont know why this error occur and why this script prevent to error. but this script is needed. WHY?import tracebackdef apply_script(protocol, connection, config):	class GrebugfixConnection(connection):		def grenade_exploded(self, grenade):			try:				if self.name is None or self.team.spectator:					return				if grenade.team is not None and grenade.team is not self.team:					# could happen if the player changed team					return				if grenade is None:					return				for player_list in (self.team.other.get_players(), (self,)):					for player in player_list:						if player is None:							return				position = grenade.position				x = position.x				y = position.y				z = position.z				if x < 0 or x > 512 or y < 0 or y > 512 or z < 0 or z > 63:					return				x = int(x)				y = int(y)				z = int(z)				for player_list in (self.team.other.get_players(), (self,)):					for player in player_list:						if not player.hp:							continue						damage = grenade.get_damage(player.world_object.position)				return connection.grenade_exploded(self, grenade)			except:				print "!!!! error protected code: G5  in aht_gbf grenade_exploded !!!!"				traceback.print_exc()				return	return protocol, GrebugfixConnection